---
pagetitle: Rmd report
output:
  html_document:
    highlight: zenburn
    theme: cosmo
    df_print: paged
    toc: yes
    code_folding: hide
    code_download: true
---

```{r r_setup, include = FALSE}
## initial settings
knitr::opts_chunk$set(
  comment = NA,
  echo = TRUE,
  error = TRUE,
  cache = FALSE,
  message = FALSE,

  dpi = 96,
  warning = FALSE
)

## width to use when printing tables etc.
options(
  width = 250,
  scipen = 100,
  max.print = 5000,
  stringsAsFactors = FALSE
)

## make all required libraries available by loading radiant package if needed
if (is.null(shiny::getDefaultReactiveDomain())) library(radiant)

## include code to load the data you require
## for interactive use attach the r_data environment
# attach(r_data)
```

<style>
.btn, .form-control, pre, code, pre code {
  border-radius: 4px;
}
.table {
  width: auto;
}
ul, ol {
  padding-left: 18px;
}
code, pre, pre code {
  overflow: auto;
  white-space: pre;
  word-wrap: normal;
}
code {
  color: #c7254e;
  background-color: #f9f2f4;
}
pre {
  background-color: #ffffff;
}
</style>

## Your report title


```{r}
## Load commands
X20211026_processed <- readr::read_csv("20211026_processed.csv", n_max = Inf) %>%
  fix_names() %>%
  to_fct()
register("X20211026_processed")
```


```{r fig.width = 6.46, fig.height = 8.62, dpi = 96}
result <- pre_factor(
  X20211026_processed, 
  vars = c(
    "refresh", "mentalhealth", "immunity", "bodypain", "goodsleep", 
    "enjoymeal", "friendship", "traveler", "pleasure", "skinbeauty", 
    "metabolism", "detox", "diet", "coworkingspace", "relaxspace"
  )
)
summary(result, dec = 2)
plot(result, plots = c("scree", "change"), custom = FALSE)
```

```{r fig.width = 7.54, fig.height = 18.85, dpi = 96}
result <- full_factor(
  X20211026_processed, 
  vars = c(
    "refresh", "mentalhealth", "immunity", "bodypain", "goodsleep", 
    "enjoymeal", "friendship", "traveler", "pleasure", "skinbeauty", 
    "metabolism", "detox", "diet", "coworkingspace", "relaxspace"
  ), 
  nr_fact = 5
)
summary(result, cutoff = 0, fsort = TRUE, dec = 2)
plot(result, custom = FALSE)
X20211026_processed <- store(X20211026_processed, result, name = "factor")
```


```{r}
## rename variable(s)
X20211026_processed <- dplyr::rename(X20211026_processed, Beauty = factor1)
## rename variable(s)
X20211026_processed <- dplyr::rename(X20211026_processed, Work_Performance = factor4)
## rename variable(s)
X20211026_processed <- dplyr::rename(X20211026_processed, Fun_Experience = factor3)
## rename variable(s)
X20211026_processed <- dplyr::rename(X20211026_processed, Health = factor5)
## rename variable(s)
X20211026_processed <- dplyr::rename(X20211026_processed, Friendship_and_Coworkingspace = factor2)
```


```{r fig.width = 9.69, fig.height = 8.62, dpi = 96}
result <- hclus(
  X20211026_processed, 
  vars = c(
    "Beauty", "Work_Performance", 
    "Fun_Experience", "Health", 
    "Friendship_and_Coworkingspace"
  )
)
summary(result)
plot(result, plots = "dendro", custom = FALSE)
```



```{r fig.width = 8.08, fig.height = 9.69, dpi = 96}
result <- kclus(
  X20211026_processed, 
  vars = c(
    "Beauty", "Work_Performance", 
    "Fun_Experience", "Health", 
    "Friendship_and_Coworkingspace"
  ), 
  nr_clus = 6, 
  standardize = FALSE
)
summary(result, dec = 2)
plot(result, plots = "bar", custom = FALSE)
X20211026_processed <- store(X20211026_processed, result, name = "Segment")
```


```{r}
## recode variable
X20211026_processed <- mutate(X20211026_processed, Segment_rc = car::Recode(Segment, "1='Biishiki';2='Otsukiai';3='Business person';4='Totonoi seeker';5='Body recovery';6='Sauna mankitsu'"))
```

```{r fig.width = 7, fig.height = 4.31, dpi = 96}
result <- regress(
  X20211026_processed, 
  rvar = "expenditure", 
  evar = "Segment_rc"
)
summary(result)
plot(result, plots = "coef", intercept = TRUE, incl = "Segment_rc", custom = FALSE)
```

```{r fig.width = 7, fig.height = 8.62, dpi = 96}
result <- cross_tabs(
  X20211026_processed, 
  var1 = "Segment_rc", 
  var2 = "gender"
)
summary(result, check = c("observed", "expected"))
plot(result, check = c("observed", "expected"), custom = FALSE)
```


```{r fig.width = 7, fig.height = 8.62, dpi = 96}
result <- cross_tabs(
  X20211026_processed, 
  var1 = "Segment_rc", 
  var2 = "age"
)
summary(result, check = c("observed", "expected"))
plot(result, check = c("observed", "expected"), custom = FALSE)
```


```{r fig.width = 7, fig.height = 8.62, dpi = 96}
result <- cross_tabs(
  X20211026_processed, 
  var1 = "Segment_rc", 
  var2 = "family"
)
summary(result, check = c("observed", "expected"))
plot(result, check = c("observed", "expected"), custom = FALSE)
```


```{r fig.width = 7, fig.height = 8.62, dpi = 96}
result <- cross_tabs(
  X20211026_processed, 
  var1 = "Segment_rc", 
  var2 = "education"
)
summary(result, check = c("observed", "expected"))
plot(result, check = c("observed", "expected"), custom = FALSE)
```

```{r fig.width = 10, fig.height = 8.62, dpi = 96}
result <- cross_tabs(
  X20211026_processed, 
  var1 = "gender", 
  var2 = "Segment_rc"
)
summary(result, check = c("observed", "expected"))
plot(result, check = c("observed", "expected"), custom = FALSE)
```


```{r fig.width = 10, fig.height = 8.62, dpi = 96}
result <- cross_tabs(
  X20211026_processed, 
  var1 = "age", 
  var2 = "Segment_rc"
)
summary(result, check = c("observed", "expected"))
plot(result, check = c("observed", "expected"), custom = FALSE)
```


```{r fig.width = 10, fig.height = 8.62, dpi = 96}
result <- cross_tabs(
  X20211026_processed, 
  var1 ="family", 
  var2 = "Segment_rc"
)
summary(result, check = c("observed", "expected"))
plot(result, check = c("observed", "expected"), custom = FALSE)
```


```{r fig.width = 10, fig.height = 8.62, dpi = 96}
result <- cross_tabs(
  X20211026_processed, 
  var1 = "education", 
  var2 = "Segment_rc"
)
summary(result, check = c("observed", "expected"))
plot(result, check = c("observed", "expected"), custom = FALSE)
```

